### ISSUE TITLE
Example json structure parsing 

### ISSUE THREAD

**Issue by vadimich** [noonker/json-to-org-table#1]
Hi,

Thank you for this package!

I tried to parse 2 of your example structures with the given function.

1st one works well, and outputs the expected result:
Map of Maps
`(json-to-org-table-parse-json-string "{\"glossary\": {\"title\": \"example glossary\",\"GlossDiv\": {\"title\": \"S\",\"GlossList\": {\"GlossEntry\": {\"ID\": \"SGML\",\"SortAs\": \"SGML\",\"GlossTerm\": \"Standard Generalized Markup Language\",\"Acronym\": \"SGML\",\"Abbrev\": \"ISO 8879:1986\",\"GlossDef\": {\"para\": \"A meta-markup language, used to create markup languages such as DocBook.\",\"GlossSeeAlso\": [\"GML\", \"XML\"]},\"GlossSee\": \"markup\"}}}}}")`

However, replacing the argument to the next example json structure (Vector of Maps) throws an exception:
`[{"type": "human", "name": "Manuel", "nickname": "Mannie"},
 {"type": "AI", "name": "HOLMES IV", "nickname": "Mike"},
 {"type": "human", "name": "Bernardo de la Paz", "nickname": "The Professor"}]`

`(json-to-org-table-parse-json-string "[{\"type\": \"human\", \"name\": \"Manuel\", \"nickname\": \"Mannie\"}, {\"type\": \"AI\", \"name\": \"HOLMES IV\", \"nickname\": \"Mike\"}, {\"type\": \"human\", \"name\": \"Bernardo de la Paz\", \"nickname\": \"The Professor\"}]")
`
gives the following error:

> Wrong type argument: sequencep, cur

**Comment by noonker** [comment]
I think my last push should have fixed it. Good catch! Let me know if you are still having problems!
